### ISSUE TITLE
Setup following docs

### ISSUE THREAD

**Issue by stephenstubbs** [pavouk-0/postgres-xl-docker#36] opened 2019-09-22 17:42 UTC
Hi,

Just setup clean docker installs on two machines and one 3 node docker swarm cluster to test following the docs and this is what I'm getting just for your info.

I'm cloning the master branch repo.

**1. docker-compose up**
```
Step 11/19 : RUN ./configure --prefix ${PG_LIB} &&     make &&     cd contrib/pgxc_monitor &&     make
 ---> Running in 3326fb3fc9a7
/bin/sh: 1: ./configure: not found
ERROR: Service 'db_gtm_1' failed to build: The command '/bin/sh -c ./configure --prefix ${PG_LIB} &&     make &&     cd contrib/pgxc_monitor &&     make' returned a non-zero code: 127
```

**2. docker-compose -f docker-compose.image.yml up**
Then running init-eg This works and I can read and write to cluster fine.

**3. docker stack deploy -c docker-compose.swarm.yml postgresxl**
Then running init-eg-swarm.
Getting 0/1 replicas and no logs. docker ps -a shows no containers. I've pulled the image manually to double check as I've had an issue like this in the past when docker wasn't pulling the image automatically on service creation. I'm not sure if this is an issue with the docker I'm running which is why I'm trying it on different machines. Using docker 18.09.2

**Comment by tiredpixel** [comment] 2019-09-22 17:51
> 1. docker-compose up

This is odd. Could it be that you've cloned the repository without initialising the Git submodules? Postgres-XL source is included as a submodule, locking to a specific commit, so if `lib/postgres-xl` is empty, this is probably why.

> 2. docker-compose -f docker-compose.image.yml up

That's great. How about if you change `latest` to `XL_10_R1_1-313-g31dfe47` or `XL9_5_R1_5-451-gaed0774` (I'm presuming your `latest` tag hasn't updated in recent days, which is a problem with that tag and one of various reasons why it shouldn't be used for production.)

> 3. docker stack deploy -c docker-compose.swarm.yml postgresxl

Ummm… :| :D I'm guessing this is because when I committed that example file, I included the constraint `node.labels.grp == dbxl`. Try labelling your Swarm nodes (e.g. `docker node update --label-add grp=dbxl`), or launch with all those constraints dicts deleted. If this sorts it, I'll be the first to admit it's completely non-obvious; I'll accept a patch to remove the constraints from the example file so it's clearer. :)

**Comment by tiredpixel** [comment] 2019-09-22 17:55
Oh, and p.s., Docker auto-image pulling on Swarm can be *very* broken. There's a whole load of non-obvious issues which can occur, with very few clear solutions or even errors. However, this is usually only for pulling authenticated repositories; Docker Hub public should be fine. So, although I, too, have had *lots* of problems with Swarm in the past with pulling images automatically, then I don't think it's what's hurting you, here. (And, you'll be pleased to hear if you haven't found already, Kubernetes seems to be *much* better in this regard!)

**Comment by tiredpixel** [comment] 2019-09-22 18:58
Kindly note this serious issue, which is a potential upstream bug (as yet unconfirmed and unreported):
https://github.com/pavouk-0/postgres-xl-docker/issues/37

**Comment by stephenstubbs** [comment] 2019-09-22 19:03
Thanks for letting me know. Still testing.

**Comment by stephenstubbs** [comment] 2019-09-22 19:06
issue 1 is resolved. Trying to get swarm to work properly.

**Comment by tiredpixel** [comment] 2019-09-22 19:12
Excellent.

**Comment by tiredpixel** [comment] 2019-09-22 19:17
For documentation/future-selves purposes :) , please note that Issue 3 was addressed by:
https://github.com/pavouk-0/postgres-xl-docker/pull/39
(just merged)

**Comment by stephenstubbs** [comment] 2019-09-22 19:25
ok great issue 3 was the placement constraints. Didn't help that my one dev machine has docker misbehaving for some reason. Anyway thanks a lot this can be closed.

**Comment by tiredpixel** [comment] 2019-09-22 19:30
Brilliant. Thanks for sticking with it. :)

**Closed as completed by tiredpixel** 2019-09-22 19:30 UTC
